import { AlertCircleIcon } from "lucide-react";
import Layout from "./components/layout";
import { Alert, AlertDescription, AlertTitle } from "./components/ui/alert";
import { ThemeProvider } from "./providers/theme-provider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { LIST_TABS } from "./config/constant";
import { useState } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

const App = () => {
  const [selectedTab, setSelectedTab] = useState(LIST_TABS[0].value);
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider defaultTheme="dark">
        <Layout>
          <div className="p-8 space-y-8">
            <Alert>
              <AlertCircleIcon />
              <AlertTitle>AI-Generated Insights</AlertTitle>
              <AlertDescription>
                This report is generated by an AI-powered agent and may contain
                inaccuracies. Please review findings carefully.
              </AlertDescription>
            </Alert>
            <Tabs defaultValue={selectedTab} onValueChange={setSelectedTab}>
              <TabsList>
                {LIST_TABS.map((tab) => (
                  <TabsTrigger key={tab.value} value={tab.value}>
                    <tab.icon className="w-4 h-4 mr-2" />
                    {tab.label}
                  </TabsTrigger>
                ))}
              </TabsList>
              {LIST_TABS.map((tab) => {
                return <tab.component key={tab.value} />;
              })}
            </Tabs>
          </div>
        </Layout>
      </ThemeProvider>
    </QueryClientProvider>
  );
};

export default App;
