import { AlertCircleIcon } from "lucide-react";
import Layout from "./components/layout";
import { Alert, AlertDescription, AlertTitle } from "./components/ui/alert";
import { ThemeProvider } from "./providers/theme-provider";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/ui/tabs";

const App = () => {
  return (
    <ThemeProvider defaultTheme="dark">
      <Layout>
        <div className="p-8 space-y-8">
          <Alert>
            <AlertCircleIcon />
            <AlertTitle>AI-Generated Insights</AlertTitle>
            <AlertDescription>
              This report is generated by an AI-powered agent and may contain
              inaccuracies. Please review findings carefully.
            </AlertDescription>
          </Alert>
          <Tabs defaultValue="account">
            <TabsList>
              <TabsTrigger value="account">Account</TabsTrigger>
              <TabsTrigger value="password">Password</TabsTrigger>
            </TabsList>
            <TabsContent value="account">
              <p>Account settings go here.</p>
            </TabsContent>
            <TabsContent value="password">
              <p>Password settings go here.</p>
            </TabsContent>
          </Tabs>
        </div>
      </Layout>
    </ThemeProvider>
  );
};

export default App;
